name: Java CI with Maven

on:
  push:
    branches: [ "Springboot-sql-dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
         username: ${{ vars.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3     
   

    - name : Build and push
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: gitbub-actions/app:latest

